forestry/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [


    # FORESTRY AREA
    path('', views.forestry, name='forestry'),
    path('private_tree_plantation/', views.ptpr, name='ptpr'),
    path('cov_certificate/', views.cov, name='cov'),
    path('lumber_origin/', views.clo, name='clo'),
    path('chainsaw/', views.chainsaw, name='chainsaw'),
    path('treecutting_gov/', views.treecutting_gov, name='treecutting_gov'),
    path('treecutting_public/', views.treecutting_public, name='treecutting_public'),
    path('private_land_timber/', views.pltp, name='pltp'),
    path('slup/', views.slup, name='slup'),

    
    path('flag/', views.flag, name='flag'),
    path('lumber_dealer/', views.lumber_dealer, name='lumber_dealer'),
    path('seedling_assist/', views.seedling_assist, name='seedling_assist'),
    path('wpp_permit/', views.wpp_permit, name='wpp_permit'),

    
    
    
    
    
    
    
    
    






]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

kiosk/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = "kiosk"

urlpatterns = [
    path('', views.index, name='indexx'),
    path('feedback', views.homepage, name='homepage'),


    
    
    
    
    
    
    
    
    






]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

map/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    # MAP AREA
    path('', views.map, name='map'),
    path('land_use/', views.landUse, name='landUse'),
    path('forest_management/', views.forestManagement, name='forestManagement'),
    path('protected_areas/', views.protectedAreas, name='protectedAreas'),
    path('mining_zone/', views.miningZone, name='miningZone'),
    path('gis_services/', views.gisServices, name='gisServices'),
    path('hazard_risk/', views.hazardRisk, name='hazardRisk'),


    
    
    
    
    
    
    
    
    






]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from kiosk import views
urlpatterns = [
    path('admin/overview', views.overview, name='overview'),
    path('admin/', admin.site.urls),
   
    path('biodiversity/', include(('biodiversity.urls', 'biodiversity'), namespace='biodiversity')),
    path('land/', include(('land.urls', 'land'), namespace='land')),
    path('af_Internal_and_External_Services/', include(('inExternal.urls', 'inExternal'), namespace='inExternal')),
    path('af_External_Service/', include(('external.urls', 'external'), namespace='external')),
    path('forestry/', include(('forestry.urls', 'forestry'), namespace='forestry')),
    path('map/', include(('map.urls', 'map'), namespace='map')),
    path('', include(('kiosk.urls'), namespace='kiosk')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forestry/models.py
from django.db import models
from django.utils import timezone



class PTPRApplication(models.Model):
    fullname = models.CharField(max_length=255, verbose_name="Full Name",blank=False)

    letter_request = models.FileField(upload_to='ptpr/letter_requests/',verbose_name="Letter Request",blank=True,null=True)
    brgy_certificate = models.FileField(upload_to='ptpr/brgy_certificates/',verbose_name="Brgy. Certificate",blank=True,null=True)
    land_title_or_tax_declaration = models.FileField(upload_to='ptpr/land_titles/',verbose_name="Land Title or Tax Declaration",blank=True,null=True)
    spa_document = models.FileField(upload_to='ptpr/spa_documents/',verbose_name="SPA Document",blank=True,null=True)
    valid_id_with_signature = models.FileField(upload_to='ptpr/valid_ids/',verbose_name="Valid ID with Signature",blank=True,null=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname
    
    class Meta:
        verbose_name = "Private Tree Plantation"
        verbose_name_plural = "Private Tree Plantation"
    

class COVApplication(models.Model):
    fullname = models.CharField(max_length=255)
    plantation = models.CharField(max_length=500)
    species = models.CharField(max_length=255)
    volume_cubic = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)

    STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('disapproved', 'Disapproved'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')

    remarks = models.TextField(blank=True, null=True)
    reference_no = models.CharField(max_length=50, unique=True, blank=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.reference_no:
            year = timezone.now().year
            last = COVApplication.objects.filter(reference_no__startswith=f"COV-{year}").order_by('-id').first()
            num = 1 if not last else last.id + 1
            self.reference_no = f"COV-{year}-{num:03d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.reference_no} - {self.fullname}"
    
    class Meta:
        verbose_name ="COV – Tree Transport"
        verbose_name_plural ="COV – Tree Transport"
    

class CLOApplication(models.Model):
    fullname = models.CharField(max_length=255)
    plantation = models.CharField(max_length=500)
    species = models.CharField(max_length=255)
    volume_cubic = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    destination = models.CharField(max_length=255)

    STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('disapproved', 'Disapproved'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')

    remarks = models.TextField(blank=True, null=True)
    reference_no = models.CharField(max_length=50, unique=True, blank=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.reference_no:
            year = timezone.now().year
            last = CLOApplication.objects.filter(reference_no__startswith=f"CLO-{year}").order_by('-id').first()
            num = 1 if not last else last.id + 1
            self.reference_no = f"CLO-{year}-{num:03d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.reference_no} - {self.fullname}"
    

    class Meta:
        verbose_name = "Lumber Origin(CLO)"
        verbose_name_plural = "Lumber Origin(CLO)"
    

class ChainsawRegistration(models.Model):
    fullname = models.CharField(max_length=255)
    
    dti = models.FileField(upload_to='chainsaw_registration/dti/',verbose_name="Business Name Registration(DTI)",blank=True,null=True)
    affidavit = models.FileField(upload_to='chainsaw_registration/affidavit/',verbose_name="Affidavit of Ownership(Atty.)",blank=True,null=True)
    permit_sell = models.FileField(upload_to='chainsaw_registration/permit_sell/',verbose_name="Permit to Sell",blank=True,null=True)
    purchase_receipt = models.FileField(upload_to='chainsaw_registration/purchase_receipt/',verbose_name="Purchase of Chainsaw Official Receipt",blank=True,null=True)
    application_form = models.FileField(upload_to='chainsaw_registration/application_form/',verbose_name="Application Form from DENR",blank=True,null=True)
    chainsaw_specification = models.FileField(upload_to='chainsaw_registration/chainsaw_specification/',verbose_name="Chainsaw Specification from DENR",blank=True,null=True)
    mayors_permit = models.FileField(upload_to='chainsaw_registration/mayors_permit/',verbose_name="Mayor's Permit",blank=True,null=True)
    serial_no = models.FileField(upload_to='chainsaw_registration/serial_no/',verbose_name="Stencil of Serial No.",blank=True,null=True)
    spa_document = models.FileField(upload_to='chainsaw_registration/dti/',verbose_name="SPA Document",blank=True,null=True)
    valid_id_with_signature = models.FileField(upload_to='chainsaw_registration/dti//',verbose_name="Valid ID with Signature",blank=True,null=True)

    STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('disapproved', 'Disapproved'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')

    remarks = models.TextField(blank=True, null=True)
    reference_no = models.CharField(max_length=50, unique=True, blank=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.reference_no:
            year = timezone.now().year
            last = ChainsawRegistration.objects.filter(reference_no__startswith=f"CS-{year}").order_by('-id').first()
            num = 1 if not last else last.id + 1
            self.reference_no = f"CS-{year}-{num:03d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.reference_no} - {self.fullname}"
    

    class Meta:
        verbose_name = "Chainsaw Registration"
        verbose_name_plural = "Chainsaw Registration"
    

class TreeCuttingApplication(models.Model):
    fullname = models.CharField(max_length=255)
    plantation = models.CharField(max_length=500)  # Source of Lumber
    species = models.CharField(max_length=255)

    STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('disapproved', 'Disapproved'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')

    remarks = models.TextField(blank=True, null=True)
    reference_no = models.CharField(max_length=50, unique=True, blank=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.reference_no:
            year = timezone.now().year
            last = TreeCuttingApplication.objects.filter(reference_no__startswith=f"TCLO-{year}").order_by('-id').first()
            num = 1 if not last else last.id + 1
            self.reference_no = f"TCLO-{year}-{num:03d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.reference_no} - {self.fullname}"
    

    class Meta:
        verbose_name = "Tree Cutting (National)"
        verbose_name_plural = "Tree Cutting (National)"
    

class TreeCuttingPublicApplication(models.Model):
    fullname = models.CharField(max_length=255)
    plantation = models.CharField(max_length=500)  # Source of Lumber / Facility
    species = models.CharField(max_length=255)
    volume = models.DecimalField(max_digits=6, decimal_places=2, help_text="Volume in cubic meters")

    STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('disapproved', 'Disapproved'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')

    remarks = models.TextField(blank=True, null=True)
    reference_no = models.CharField(max_length=50, unique=True, blank=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.reference_no:
            year = timezone.now().year
            last = TreeCuttingPublicApplication.objects.filter(reference_no__startswith=f"TCP-{year}").order_by('-id').first()
            num = 1 if not last else last.id + 1
            self.reference_no = f"TCP-{year}-{num:03d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.reference_no} - {self.fullname}"
    
    class Meta:
        verbose_name = "Tree Cutting (Public)"
        verbose_name_plural = "Tree Cutting (Public)"
    

class PrivateLandTimberPermit(models.Model):
    fullname = models.CharField(max_length=255)
    lot_location = models.CharField(max_length=500)
    tree_type = models.CharField(max_length=255)
    volume = models.DecimalField(max_digits=6, decimal_places=2, help_text="Volume in cubic meters")

    STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('disapproved', 'Disapproved'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')
    remarks = models.TextField(blank=True, null=True)
    reference_no = models.CharField(max_length=50, unique=True, blank=True)

    date_submitted = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.reference_no:
            year = timezone.now().year
            last = PrivateLandTimberPermit.objects.filter(reference_no__startswith=f"LOP-{year}").order_by('-id').first()
            num = 1 if not last else last.id + 1
            self.reference_no = f"LOP-{year}-{num:03d}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.reference_no} - {self.fullname}"
    
    class Meta:

forestry/forms.py
from django import forms
from .models import PTPRApplication,COVApplication,CLOApplication,ChainsawRegistration,TreeCuttingApplication,TreeCuttingPublicApplication,PrivateLandTimberPermit,SLUPApplication,FLAGApplication,LumberDealerApplication,SeedlingRequest,WPPPermit

class PTPRApplicationForm(forms.ModelForm):
    class Meta:
        model = PTPRApplication
        fields = [
            'fullname',
            'letter_request',
            'brgy_certificate',
            'land_title_or_tax_declaration',
            'spa_document',
            'valid_id_with_signature',
        ]


class COVApplicationForm(forms.ModelForm):
    class Meta:
        model = COVApplication
        fields = ['fullname', 'plantation', 'species', 'volume_cubic']


class CLOApplicationForm(forms.ModelForm):
    class Meta:
        model = CLOApplication
        fields = ['fullname', 'plantation', 'species', 'volume_cubic', 'destination']


class ChainsawRegistrationForm(forms.ModelForm):
    class Meta:
        model = ChainsawRegistration
        fields = [
            'fullname',
            'dti',
            'affidavit',
            'permit_sell',
            'purchase_receipt',
            'application_form',
            'chainsaw_specification',   
            'mayors_permit',
            'serial_no',
            'spa_document',
            'valid_id_with_signature',
        ]


class TreeCuttingApplicationForm(forms.ModelForm):
    class Meta:
        model = TreeCuttingApplication
        fields = ['fullname', 'plantation', 'species']


class TreeCuttingPublicForm(forms.ModelForm):
    class Meta:
        model = TreeCuttingPublicApplication
        fields = ['fullname', 'plantation', 'species', 'volume']


class PrivateLandTimberPermitForm(forms.ModelForm):
    class Meta:
        model = PrivateLandTimberPermit
        fields = ['fullname', 'lot_location', 'tree_type', 'volume']


class SLUPApplicationForm(forms.ModelForm):
    class Meta:
        model = SLUPApplication
        fields = ['fullname', 'location', 'project']


class FLAGApplicationForm(forms.ModelForm):
    class Meta:
        model = FLAGApplication
        fields = ['fullname', 'project_type', 'location']


class LumberDealerForm(forms.ModelForm):
    class Meta:
        model = LumberDealerApplication
        fields = ['fullname', 'plantation', 'species', 'volume']


class SeedlingRequestForm(forms.ModelForm):
    class Meta:
        model = SeedlingRequest
        fields = ['fullname', 'species', 'quantity']


class WPPPermitForm(forms.ModelForm):
    class Meta:
        model = WPPPermit
        fields = ['applicant', 'location', 'capacity']

kiosk/forms.py
# main_app/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ["app_name", "message"]
        widgets = {
            "app_name": forms.Select(attrs={"class": "form-control"}),
            "message": forms.Textarea(attrs={"rows": 4, "class": "form-control"}),
        }

kiosk/views.py
from django.shortcuts import render, redirect
from .forms import FeedbackForm
from django.http import HttpResponse


# Create your views here.

def index(request):
    return render(request, 'index.html')


def homepage(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("homepage")  # balik sa homepage pagkatapos magsubmit
    else:
        form = FeedbackForm()

    return render(request, "home.html", {"form": form})


def overview(request):
    return render(request,'overview/index.html')

templates/kiosk/forestry/forestry.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Forestry Services | PENRO</title>
  <link rel="stylesheet" href="{% static 'css/forestry-style.css' %}" />
</head>
<body>
  <a href="{% url 'kiosk:indexx' %}" class="back-button" title="Go Back">&#8592; Back</a>

  <div class="services-container">
    <h1>Forestry Services</h1>

    <div class="service-list">

      <a href="{% url 'forestry:ptpr' %}" class="service-card">
        <h3>🌲 Private Tree Plantation Registration (PTPR)</h3>
        <p>Issuance of Private Tree Plantation Registration (PTPR).</p>
      </a>

      <a href="{% url 'forestry:cov' %}" class="service-card">
        <h3>📜 Transport Clearance for Planted Trees & Non-Timber Products (Except Rattan/Bamboo)</h3>
        <p>Issuance of Certificate of Verification (COV) for the
        Transport of Planted Trees within Private Land, Nontimber Forest Products Except Rattan and Bamboo
        </p>
      </a>

      <a href="{% url 'forestry:clo' %}" class="service-card">
        <h3>📦 Certificate of Lumber Origin (CLO) for Processed Logs</h3>
        <p>Issuance of Certificate of Lumber Origin (CLO) Processed
        Logs/Lumber from Wood Processing Plant (WPP) to other
        WPP or Desired Destination/s
        </p>
      </a>

      <a href="{% url 'forestry:chainsaw' %}" class="service-card">
        <h3>🪚 Chainsaw Registration Application</h3>
        <p>Application for Chainsaw Registration</p>
      </a>

      <a href="{% url 'forestry:treecutting_gov' %}" class="service-card">
        <h3>✂️ Tree Cutting/Earth Balling Permit for Government Projects</h3>
        <p>Issuance of Tree Cutting and/or Earth Balling Permit for
        Trees Affected by Projects of National Government
        Agencies (DPWH, DOTr, DepEd, DA, DOH, CHED, DOE, and
        NIA)
        </p>
      </a>

      <a href="{% url 'forestry:treecutting_public' %}" class="service-card">
        <h3>🏞️ Tree Cutting Permit in Public Areas for Safety Purposes</h3>
        <p>Issuance of Tree Cutting Permit for Planted Trees and
          Naturally Growing Trees Found within Public Places (Plaza,
          Public Parks, School Premises or Political Subdivisions) for
          purposes of Public Safety</p>
      </a>

      <a href="{% url 'forestry:pltp' %}" class="service-card">
        <h3>🪵 Timber Permit for Trees on Private Lands (PLTP/SPLTP)</h3>
        <p>Issuance of Private Land Timber Permit (PLTP) for Nonpremium Species, or Special PLTP (SPLTP) for
            Premium/Naturally-grown Trees within Private/Titled
            Lands</p>
      </a>

      <a href="{% url 'forestry:slup' %}" class="service-card">
        <h3>📄 Special Land Use Permit (SLUP) Application</h3>
        <p> Issuance of Special Land Use Permit (SLUP) </p>
      </a>

      <a href="{% url 'forestry:flag' %}" class="service-card">
        <h3>📘 Forest Land Use Agreement (FLAg) Issuance</h3>
        <p>Issuance of Forest Land Use Agreement (FLAg).</p>
      </a>

      <a href="{% url 'forestry:lumber_dealer' %}" class="service-card">
        <h3>🪵 Lumber Dealer Registration Certificate</h3>
        <p>Issuance of Certificate of Registration as Lumber Dealer </p>
      </a>

      <a href="{% url 'forestry:seedling_assist' %}" class="service-card">
        <h3>🌿 Seedling Request & Technical Assistance</h3>
        <p>Provision for Technical Assistance in Relation to Seedling
          Request
          </p>
      </a>

      <a href="{% url 'forestry:wpp_permit' %}" class="service-card">
        <h3>🏭 New Wood Processing Plant (WPP) Permit Processing</h3>
        <p>Processing and Endorsement of Wood Processing Plant
          (WPP) Permit (New)</p>
      </a>

    </div>

  </div>
</body>
</html>

templates/kiosk/forestry/tree-cutting-public.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Tree Cutting Public| PENRO</title>
  <link rel="stylesheet" href="{% static 'css/forestry2-style.css' %}" />
  
</head>
<body>
  <a href="{% url 'forestry:forestry' %}" class="back-button" title="Back to Forestry Services">&#8592; Back</a>

  <div class="container" style="max-height: 96vh;overflow-y: auto;padding: 20px;box-sizing: border-box;">
    <h1>🪵 Tree Cutting Public</h1>


    <section class="card">
        <h2>📘 What is a Tree Cutting Public</h2>
        <p>
            The Certificate of Lumber Origin (CLO) is issued by the DENR for the transport of processed logs/lumber from a Wood Processing Plant (WPP) to another WPP or desired destination. This ensures the legality and traceability of forest products during transport.
        </p>
    </section>


    <section class="card">
        <h2>📄 Purpose of the Tree Cutting Puclic</h2>
        <ul>
            <li>Verifies the legal source of processed logs or lumber</li>
            <li>Supports DENR enforcement and monitoring</li>
            <li>Facilitates inter-WPP transport and lumber trade</li>
        </ul>
    </section>



    <div class="container" >

      <div class="options">
        <div class="option active" onclick="showContent('chart')" style="color: #1b5e20;">CITIZEN’S CHARTER</div>
        <div class="option" onclick="showContent('form')" style="color: #1b5e20;">Registration Form</div>
        <div class="option" onclick="showContent('status')" style="color: #1b5e20;">Status</div>
      </div>

      <div class="content" id="chartContent">
        <h2 style="color: rgba(40, 167, 69, 1); margin-bottom: 20px;">CITIZEN’S CHARTER NO. R8-F-06. ISSUANCE OF TREE CUTTING PERMIT FOR PLANTED TREES AND NATURALLY GROWING TREES FOUND WITHIN PUBLIC PLACES (PLAZA, PUBLIC PARKS, SCHOOL PREMISES OR POLITICAL SUBDIVISIONS) FOR PURPOSES     OF  PUBLIC SAFETY
        </h2>
        <h4>This Permit serves as proof of authorization for the removal/cutting of trees in public places (Plaza, Public Parks, School
          Premises or Political Subdivisions for purposes of public safety).
        </h4>

        <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%;">
          <tr>
            <th style="width: 30%; background-color: #c2e1f8;">Office or Division:</th>
            <td>Regulation and Permitting Section, Implementing PENR/CENR Office</td>
          </tr>
          <tr>
            <th style="background-color: #c2e1f8;">Classification:</th>
            <td>Highly Technical</td>
          </tr>
          <tr>
            <th style="background-color: #c2e1f8;">Type of Transaction:</th>
            <td>G2C - Government to Citizen<br>G2G - Government to Government<br>G2B - Government to Business</td>
          </tr>
          <tr>
            <th style="background-color: #c2e1f8;">Who may avail:</th>
            <td>Any Filipino citizen, Local Government Units (LGUs), Schools, Homeowners</td>
          </tr>
          <tr style="background-color: #c2e1f8;">
            <th style="text-align: center;">CHECKLIST OF REQUIREMENTS</th>
            <th style="text-align: center;">WHERE TO SECURE</th>
          </tr>
          <tr>
            <td>1. Application Letter (1 original)</td>
            <td>Requesting Party</td>
          </tr>
          <tr>
            <td>2. LGU Endorsement/Certification of No Objection/Resolution (1 original)</td>
            <td>Concerned LGU (City/Municipal/Barangay)</td>
          </tr>
          <tr style="background-color: #c2e1f8;">
            <td><strong>3. Additional Requirements</strong></td>
            <td></td>
          </tr>
          <tr style="background-color: #c2e1f8;">
            <td><strong>if within Subdivisions</strong></td>
            <td></td>
          </tr>
          <tr>
            <td>Homeowner's Resolution (1 original/1 Certified True Copy)</td>
            <td>Homeowner's Association</td>
          </tr>
          <tr style="background-color: #c2e1f8;">
            <td><strong>if School/Organization</strong></td>
            <td></td>
          </tr> 
          <tr>
            <td>PTA Resolution or Resolution from any organized group of No Objection and Reason for Cutting (1 original)</td>
            <td>Requesting Party, School PTA, or Organization</td>
          </tr>
        </table>



      </div>

      <div class="content" id="formContent" style="display: none;">
          <form method="post" action="{% url 'forestry:treecutting_public' %}">
              {% csrf_token %}
              {{ form.as_p }}
              <button style="margin-top: 30px;" type="submit" class="btn-submit">📤 Submit Verification Request</button>
          </form>
      </div>

      <div class="content" id="statusContent" style="display: none;">
          <h2 class="section-title">📊 Tree Cutting Application Status</h2>
          <p>Below is the list of submitted Tree Cutting Permit applications and their current status.</p>

          <table class="status-table">
              <thead>
                  <tr>
                      <th>Reference No.</th>
                      <th>Applicant Name</th>
                      <th>Tree Species</th>
                      <th>Volume (m³)</th>
                      <th>Status</th>
                      <th>Remarks</th>
                  </tr>
              </thead>
              <tbody>
                  {% for app in applications %}
                  <tr>
                      <td>{{ app.reference_no }}</td>
                      <td>{{ app.fullname }}</td>
                      <td>{{ app.species }}</td>
                      <td>{{ app.volume }}</td>
                      <td class="status-{{ app.status|lower }}">{{ app.get_status_display }}</td>
                      <td>{{ app.remarks }}</td>
                  </tr>
                  {% empty %}
                  <tr>
                      <td colspan="6">No applications found.</td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>

    </div>


  </div>

<script>
  function showContent(type) {
    const tabs = document.querySelectorAll('.option');
    const contents = {
      chart: document.getElementById('chartContent'),
      form: document.getElementById('formContent'),
      status: document.getElementById('statusContent')
    };

    // remove active sa lahat
    tabs.forEach(tab => tab.classList.remove('active'));
    // hide lahat ng content
    Object.values(contents).forEach(content => content.style.display = 'none');

    // activate yung pinili
    if (type === 'chart') {
      tabs[0].classList.add('active');
      contents.chart.style.display = 'block';
    } else if (type === 'form') {
      tabs[1].classList.add('active');
      contents.form.style.display = 'block';
    } else if (type === 'status') {
      tabs[2].classList.add('active');
      contents.status.style.display = 'block';
    }
  }
</script>




</body>
</html>